spring:
    application:
        name: sis-bank-borrowing
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update
    datasource:
        platform: postres
        url: jdbc:postgresql://swiftpay-postgres-1:5432/borrowing
        username: postgres
        password: admin

    data:
        mongodb:
            host: swiftpay-mongo-1
            port: 27017
            database: sis-bank
eureka:
    client:
        service-url:
            defaultZone:
                http://swiftpay-eureka-1:8761/eureka
server:
    port: 8083
